[default]
remappings = ['test/=test/', '@uniswap/=lib/']
[ci]
fuzz_runs = 10000
remappings = ['test/=test/', '@uniswap/=lib/']
[hook]
remappings = ['test/=test/', '@uniswap/=lib/']
# See more config options https://github.com/gakonst/foundry/tree/master/config