name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts-periphery/
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build contracts
        run: |
          forge --version
          forge build --sizes
  tests:
    runs-on: ubuntu-latest
    env:
      FOUNDRY_PROFILE: ci
      ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
    defaults:
      run:
        working-directory: contracts-periphery/
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: make test
